- mbed-trace/mbed_trace.h
@SeppoTakalo @jupe @marhil01 @yogpan01 
It might be better to remove the default TRACE_GROUP definition as it may cause TRACE_GROUP refinition issues for users.
I added this default definition here mainly to avoid any compilation fails in case user tries to use tracing functions, but has not defined any TRACE_GROUP's.
> remove default TRACE_GROUP

- test/Test.cpp
there was obsolete compiler flag in unit tests
> fix ipv6 activate flag for unit tests

- test/Test.cpp
Improved test coverage by enabling a test for a function that was previously not compiled.
Fixed valgrind error by reducing the size of a very long string a little (still a very long string).
> Improved test coverage and fixed valgrind error.

- mbed-trace/mbed_trace.h
Function declarations always exist, but when tracing is disabled they are hidden by the dummy macros.
> Reworked header.

- mbed-trace/mbed_trace.h
- source/mbed_trace.c
Allows writing printf-style wrappers for the trace call.
@jupe @kjbracey-arm
> Added a vprintf style trace function.

- source/mbed_trace.c
- test/Test.cpp
If the prefix function was set, mbed_vtracef would pass ap to vsnprintf to
determine the output length, then use ap again for the actual output,
running off the real arguments.
Create a copy of ap for the initial scan. (Thank you to C99, who added
va_copy. Would have been stuck without it.)
> Fix #34: Do not try to use a va_list twice

- source/CMakeLists.txt
@jupe 
This won't build in yotta if nanostack-libservice library is not included when linking.
> Add nanostack-libservice lib to CMakeLists

- mbed-trace/mbed_trace.h
There are multiple build environments that all use different configuration methods,
which results in multiple supported trace enable flags.
This ensures that regardless of which flag/combination of flags was used to enable traces
at least one flag, FEA_TRACE_SUPPORT, is always set.
> FEA_TRACE_SUPPORT flag is always set when traces are enabled.

- source/mbed_trace.c
Configuring the tmp line length value through config.json in yotta requires defining a separate "mtrace" group, because the name of the flag doesn't follow the 'YOTTA_CFG_MBED_TRACE_' pattern.
This allows configuring the tmp line length in the same group mbed-trace is enabled in.
(The name of the flag seems to be a relic of the time the name of the library was still being decided.
For some reason it wasn't changed with the other ones when 'mbed-trace' was decided on.)
> Deprecate the misnamed YOTTA_CFG_MTRACE_TMP_LINE_LENGTH flag.

- README.md
- mbed-trace/mbed_trace.h
- source/mbed_trace.c
- test/Test.cpp
Previously only the existence of the flag was checked. Thus tracing was always enabled if the flag was defined regardless of its actual value, including when it was defined as 0 or false.
Now tracing is enabled when YOTTA_CFG_MBED_TRACE is defined as an empty define (which was previously accepted), 1 or true.
Tracing is disabled when the flag is undefined, or defined as 0 or false.
> Fix disabling traces through the YOTTA_CFG_MBED_TRACE flag.

- README.md
- source/mbed_trace.c
Calling mbed_trace_init() set the callbacks to NULL so they had to be set after initializing the library.
This left a small window of time during which traces could happen without any thread safety being in place.
> Allow setting mutex locking/unlocking callbacks before trace init.

- README.md
Decided to clean up this a bit, therefore created a branch.
> Editorial changes.

- README.md
Added instructions for enabling the tracing API in mbed OS 5.
Also slightly clarified the text to avoid implying that simply enabling the API is sufficient to enable tracing.
> Add instructions for enabling the library in mbed OS 5.

- source/mbed_trace.c
Fixes issue where mutex might be left locked when leaving mbed_vtracef function because of decreasing mutex_lock_count after releasing the mutex.
> Fix race condition when unlocking mutex

- source/mbed_trace.c
Fix in #51 still had possibility of unexpected behavior as the mutex_lock_count variable might get modified after releasing mutex during last loop iteration.
> Use temp variable in mutex release loop

- mbed-trace/mbed_trace.h
Currently e.g. Nanomesh-applications contains > 2500 tr_debug calls.
This will cause a huge impact to flash size
If app developer is only interested of error traces, he still had to include all the other traces as well to his build.
This can now be tackled by defining MBED_TRACE_MAX_LEVEL, which will leave out every unneeded trace functions from builds.
> Flash size can be limited by defining MBED_TRACE_MAX_LEVEL

- README.md
- mbed-trace/mbed_trace.h
- mbed_lib.json
- source/mbed_trace.c
- test/Test.cpp
* MBED_TRACE_LINE_LENGTH
default max trace line size in bytes
* MBED_TRACE_TMP_LINE_LENGTH
default max temporary buffer size in bytes,
used by trace_ipv6, trace_ipv6_prefix and trace_array
* MBED_TRACE_FILTER_LENGTH
default maximum length available to include and exclude filters in bytes
* MBED_TRACE_CONFIG
default trace configuration bitmask
-------
* Add support for MBED_CONF_MBED_TRACE_FEA_IPV6 flag.
-------
* Allow configuration before initialization at runtime.
* Add testcases:
Resize main trace buffer.
Configure library before initialization at runtime.
> Provide environment-agnostic configuration macros.

- source/mbed_trace.c
- test/Test.cpp
tr_array(NULL, 0) would output `"<null>"` - this is unhelpful, as
a number of parts of the system regard (NULL, 0) as being a legal
empty value. Make this output `""` instead.
> Ensure tr_array doesn't print <null> when len == 0

- mbed-trace/mbed_trace.h
**READY**
This is fixing issue #70:  when `MBED_CONF_MBED_TRACE_ENABLE=0` and application uses return value from `mbed_trace_init()` - `mbed_trace` didn't define dummy macro right way and causes compling error: 
```
a value of type "void" cannot be assigned to an entity of type "int"
```
> fix dummydefine for mbed_trace_init

- README.md
If trace helpers are used the mutex must be counting. This was previously mentioned in the header but not in the README.
Addresses #74
> Clarify mutex type requirement

- mbed-trace/mbed_trace.h
This library only uses types which are defined in `stdint.h` or `stdbool.h`, therefore it does not need dependency to Namesh libservices, which have much more compiler tweaks.
> Remove dependency to Nanomesh headers

- README.md
The filtering capabilities of mbed-trace are not covered in the README.md
at all currently, a few examples how they could be used.
> README.md / filtering examples

- source/mbed_trace.c
If one called mbed_trace_free() but continued using the trace (which
is a supported use case), the already freed tmp_data buffer was used
by tr_array().
This was spotted by Valgrind on some unit tests which do enable the
trace only temporarily for some of the tests.
Error being fixed in this PR:
```
--8<--8<--8<---
==5865== Invalid write of size 1
==5865==    at 0x2639BB: mbed_trace_array (mbed_trace.c:569)
<...>
==5865==  Address 0x5dc79d0 is 0 bytes inside a block of size 128 free'd
==5865==    at 0x4C32D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==5865==    by 0x262723: mbed_trace_free (mbed_trace.c:192)
<...>
==5865==  Block was alloc'd at
==5865==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==5865==    by 0x262548: …
```
> tr_array: fix use after free error after mbed_trace_free() is called

- mbed-trace/mbed_trace.h
These changes should get rid of:
mbed-trace/mbed_trace.h:414:53: warning: statement with no effect [-Wunused-value]
414 | #define mbed_trace_init(...)                        ((int) 0)
and unused function definition warnings regarding mbed-trace mutex functions.
> Reduce warnings when traces are disabled

- mbed_lib.json
- source/mbed_trace.c
https://github.com/ARMmbed/mbed-os/pull/14576
> Synchronize output formatting with latest Mbed OS

- CMakeLists.txt
- exposed mbedTraceInterface
- limit tests creation only when test_all flag is ON or when cmake from current directory
- do not exclude tests from "make all"
- removed check target
> Cmake add interface lib

- mbed-trace-mbed.cmake
- mbed-trace.cmake
Use separate CMakeFiles for Mbed OS builds and other builds.
> Reorganize CMakeFiles based on target
